<?php

namespace Database\Seeders;

use App\Models\Ville;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villes = [
            // Tanger-Tétouan-Al Hoceima
            'Tanger',
            'Tétouan',
            'Al Hoceima',
            'Larache',
            'Ksar El Kebir',
            'Chefchaouen',
            'Martil',
            'M\'diq',
            'Fnideq',
            'Ouazzane',
            'Asilah',
            'Bab Taza',
            'Zoumi',
            'Moqrisset',
            'Brikcha',
            'Ajdir',
            'Targuist',

            // Oriental
            'Oujda',
            'Nador',
            'Berkane',
            'Taourirt',
            'Jerada',
            'El Aioun Sidi Mellouk',
            'Guercif',
            'Taounate',
            'Bouarfa',
            'Figuig',
            'Ahfir',
            'Sidi Slimane Echcharraa',
            'Zaio',
            'Al Aaroui',
            'Bin Anşār',
            'Bouhdila',
            'Selouane',
            'Ben Taieb',
            'Driouch',
            'Midar',
            'Farkhana',
            'Tafersit',
            'Tizi Ouasli',
            'Tiztoutine',
            'Kassita',
            'Kerouna',
            'Bni Chiker',
            'Saidia',
            'Kariat Arkmane',
            'Bni Drar',
            'Touissit',

            // Fès-Meknès
            'Fès',
            'Meknès',
            'Taza',
            'Sefrou',
            'El Hajeb',
            'Ifrane',
            'Moulay Yacoub',
            'Azrou',
            'Bhalil',
            'Imouzzer Kandar',
            'Ribat El Kheir',
            'Ain Taoujdate',
            'Agourai',
            'Boumia',
            'El Menzel',
            'M\'Rirt',
            'Midelt',
            'Ait Ishaq',
            'Amalou Ighriben',
            'Itzer',
            'Kehf Nsour',
            'Moulay Bouazza',
            'El Kbab',
            'Sabaa Aiyoun',
            'Sebt Jahjouh',
            'Tiddas',
            'Ain Leuh',
            'Moulay Driss Zerhoun',
            'Boulman',
            'Missour',
            'Outat El Haj',
            'Imouzzer Marmoucha',
            'Aknoul',
            'Matmata',
            'Ghafsai',
            'Tissa',
            'Tainaste',
            'Kerrouchen',
            'Bni Hadifa',
            'Tamassint',
            'Issaguen',
            'Oued Amlil',
            'Bab Berred',
            'Thar Essouk',
            'Ain Karma',
            'Karia Ba Mohamed',
            'Gourrama',

            // Rabat-Salé-Kénitra
            'Rabat',
            'Salé',
            'Kénitra',
            'Khemisset',
            'Skhirat',
            'Témara',
            'Sidi Kacem',
            'Sidi Slimane',
            'Sidi Yahya El Gharb',
            'Souk Larbaa',
            'Mehdya',
            'Lalla Mimouna',
            'Sidi Taibi',
            'Ain El Aouda',
            'Bouknadel',
            'Harhoura',
            'Oulmes',
            'Maaziz',
            'Rommani',
            'Sidi Allal El Bahraoui',
            'Tifelt',
            'Had Kourt',
            'Mechra Bel Ksiri',
            'Jorf El Melha',
            'Moulay Bousselham',
            'Tnin Sidi Lyamani',
            'Skhinate',
            'Gueznaia',

            // Béni Mellal-Khénifra
            'Beni Mellal',
            'Khenifra',
            'Kasba Tadla',
            'Fkih Ben Saleh',
            'Azilal',
            'Demnate',
            'Ouaouizert',
            'Afourar',
            'Foum Jamaa',
            'Boujniba',
            'Aghbala',
            'Bradia',
            'Dar Ould Zidouh',
            'Oulad Mbarek',
            'Oulad Ayad',
            'Zaouiat Cheikh',

            // Casablanca-Settat
            'Casablanca',
            'Settat',
            'Mohammedia',
            'El Jadida',
            'Berrechid',
            'Ben Slimane',
            'Khouribga',
            'Boujad',
            'Wad Zam',
            'Oued Zem',
            'Bouznika',
            'Lahraouyine',
            'Tit Mellil',
            'Mediouna',
            'Bouskoura',
            'Nouaceur',
            'Deroua',
            'El Borouj',
            'Ben Ahmed',
            'Boulanouare',
            'Hattane',
            'Loulad',
            'Oulad Abbou',
            'Oulad M\'Rah',
            'Ras El Ain',
            'Guisser',
            'Soualem',
            'Azemmour',
            'Zmamra',
            'Ouled Frej',
            'Moulay Abdallah',
            'Sidi Ali Ben Hamdouche',
            'Bir Jdid',
            'Sebt Lamaarif',
            'Oulad Ghadbane',
            'Zrarda',

            // Marrakech-Safi
            'Marrakech',
            'Safi',
            'Essaouira',
            'Youssoufia',
            'El Kelaa des Sraghna',
            'Ben Guerir',
            'Chichaoua',
            'Ait Ourir',
            'Imintanoute',
            'Tamallalt',
            'Tahannaout',
            'Aghbalou Nssardane',
            'Assahrij',
            'Kettara',
            'Sidi Rahal',
            'Tameslouht',
            'Tamanar',
            'Sid Zouine',
            'Loudaya',
            'Amizmiz',
            'Sidi Abdallah Ghiat',
            'Moulay Brahim',
            'Oualidia',
            'Sidi Bou Othmane',
            'Lakhsas',
            'Talmest',
            'Jmaat Shaim',
            'Echemmaia',
            'Bouguedra',
            'Ighoud',
            'Oulad Amrane',
            'Lalla Takerkoust',
            'Naima',
            'Tafetachte',
            'Karia',
            'N\'Zalat Bni Amar',
            'Ahrara',

            // Drâa-Tafilalet
            'Errachidia',
            'Ouarzazate',
            'Zagora',
            'Tinghir',
            'Arfoud',
            'Rissani',
            'Goulmima',
            'Boumalne Dades',
            'Kalaat M\'Gouna',
            'Taznakht',
            'Boudnib',
            'Er-Rich',
            'Jorf',
            'Aoufous',

            // Souss-Massa
            'Agadir',
            'Taroudant',
            'Tiznit',
            'Inezgane',
            'Ait Melloul',
            'Oulad Teima',
            'Lqliaa',
            'Temsia',
            'Drarga',
            'Aourir',
            'Sidi Ifni',
            'Massa',
            'Aoulouz',
            'Tata',
            'Ait Iaaza',
            'Ouled Berhil',
            'El Guerdan',
            'Taliouine',
            'Ait Baha',
            'Chtouka Ait Baha',

            // Guelmim-Oued Noun
            'Guelmim',
            'Tan-Tan',
            'Bouizakarn',
            'Fam El Hisn',
            'El Ouatia',
            'Assa',
            'Akka',
            'Zag',

            // Laâyoune-Sakia El Hamra
            'Laâyoune',
            'Boujdour',
            'Tarfaya',
            'El Marsa',
            'Cape Bojador',
            'Smara',

            // Dakhla-Oued Ed-Dahab
            'Dakhla',
            'Es-Semara',
            'Aousserd',
            'Lagouira',

            // Autres
            'Tendrara',
            'Mhaya',
            'Oued El Heimar',
            'Sidi Boubker',
            'Sidi Rahel Chatai',
            'Oulad Tayeb',
            'Zaouiat Bougrin',
            'Dar Gueddari',
        ];
        foreach ($villes as $ville) {
            Ville::create([
                'ville' => $ville
            ]);
        }
    }
}
