<?php

namespace Database\Seeders;

use App\Models\Ville;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villes = [
            'Tanger',
            'Tétouan',
            'Al Hoceima',
            'Fnideq',
            'Larache',
            'Ksar El Kebir',
            'Chefchaouen',
            'Martil',
            'M\'diq',
            'Fnideq',
            'Ouazzane',
            'Asilah',
            'Bab Taza',
            'Zoumi',
            'Moqrisset',
            'Brikcha',
            'Ajdir',
            'Targuist',

            // Oriental (28 communes urbaines)
            'Oujda',
            'Nador',
            'Berkane',
            'Taourirt',
            'Jerada',
            'El Aioun Sidi Mellouk',
            'Guercif',
            'Taounate',
            'Taza',
            'Bouarfa',
            'Figuig',
            'Ahfir',
            'Sidi Slimane Echcharraa',
            'Zaio',
            'Al Aaroui',
            'Bin Anşār',
            'Bouhdila',
            'Selouane',
            'Ben Taieb',
            'Driouch',
            'Midar',
            'Farkhana',
            'Tafersit',
            'Tizi Ouasli',
            'Tiztoutine',
            'Kassita',
            'Kerouna',
            'Bni Chiker',

            'Fès',
            'Meknès',
            'Taza',
            'Sefrou',
            'El Hajeb',
            'Ifrane',
            'Moulay Yacoub',
            'Azrou',
            'Bhalil',
            'Imouzzer Kandar',
            'Ribat El Kheir',
            'Ain Taoujdate',
            'Agourai',
            'Boumia',
            'El Menzel',
            'M\'Rirt',
            'Midelt',
            'Khenifra',
            'Ait Ishaq',
            'Amalou Ighriben',
            'Itzer',
            'Kehf Nsour',
            'Moulay Bouazza',
            'El Kbab',
            'Sabaa Aiyoun',
            'Sebt Jahjouh',
            'Tiddas',
            'Ain Leuh',
            'Moulay Driss Zerhoun',
            'Boulman',
            'Missour',
            'Outat El Haj',
            'Imouzzer Marmoucha',

            'Rabat',
            'Salé',
            'Kénitra',
            'Khemisset',
            'Skhirat',
            'Témara',
            'Sidi Kacem',
            'Sidi Slimane',
            'Sidi Yahya El Gharb',
            'Souk Larbaa',
            'Mehdya',
            'Lalla Mimouna',
            'Sidi Taibi',
            'Ain El Aouda',
            'Bouknadel',
            'Harhoura',
            'Oulmes',
            'Maaziz',
            'Rommani',
            'Sidi Allal El Bahraoui',
            'Tifelt',
            'Had Kourt',
            'Mechra Bel Ksiri',
            'Jorf El Melha',

            'Beni Mellal',
            'Khenifra',
            'Kasba Tadla',
            'Fkih Ben Saleh',
            'Azilal',
            'Demnate',
            'Ouaouizert',
            'Afourar',
            'Foum Jamaa',
            'Boujniba',
            'Aghbala',
            'Bradia',
            'Dar Ould Zidouh',
            'Oulad Mbarek',
            'Oulad Ayad',
            'Zaouiat Cheikh',

            'Casablanca',
            'Settat',
            'Mohammedia',
            'El Jadida',
            'Berrechid',
            'Ben Slimane',
            'Khouribga',
            'Boujad',
            'Wad Zam',
            'Oued Zem',
            'Bouznika',
            'Lahraouyine',
            'Tit Mellil',
            'Mediouna',
            'Bouskoura',
            'Nouaceur',
            'Deroua',
            'El Borouj',
            'Ben Ahmed',
            'Boulanouare',
            'Hattane',
            'Loulad',
            'Oulad Abbou',
            'Oulad M\'Rah',
            'Ras El Ain',
            'Guisser',
            'Soualem',

            'Marrakech',
            'Safi',
            'Essaouira',
            'Youssoufia',
            'El Kelaa des Sraghna',
            'Ben Guerir',
            'Chichaoua',
            'Ait Ourir',
            'Imintanoute',
            'Tamallalt',
            'Tahannaout',
            'Aghbalou Nssardane',
            'Assahrij',
            'Kettara',
            'Sidi Rahal',
            'Tameslouht',
            'Tamanar',
            'Sid Zouine',
            'Loudaya',
            'Amizmiz',
            'Taliouine',
            'Sidi Abdallah Ghiat',
            'Moulay Brahim',

            'Errachidia',
            'Ouarzazate',
            'Zagora',
            'Tinghir',
            'Midelt',
            'Arfoud',
            'Rissani',
            'Goulmima',
            'Boumalne Dades',
            'Kalaat M\'Gouna',
            'Taznakht',
            'Boudnib',
            'Er-Rich',
            'Jorf',
            'Aoufous',
            'Aghbala',

            'Agadir',
            'Taroudant',
            'Tiznit',
            'Inezgane',
            'Ait Melloul',
            'Oulad Teima',
            'Lqliaa',
            'Temsia',
            'Drarga',
            'Aourir',
            'Sidi Ifni',
            'Massa',
            'Aoulouz',
            'Tata',
            'Ait Iaaza',
            'Ouled Berhil',
            'El Guerdan',
            'Taliouine',
            'Ait Baha',
            'Chtouka Ait Baha',
            'Inzgane Ait Melloul',

            'Guelmim',
            'Tan-Tan',
            'Sidi Ifni',
            'Bouizakarn',
            'Tata',
            'Fam El Hisn',
            'El Ouatia',
            'Assa',

            'Laâyoune',
            'Boujdour',
            'Tarfaya',
            'El Marsa',
            'Cape Bojador',

            'Dakhla',

            'Smara',
            'Assa',
            'Zag',
            'Boujdour',
            'Es-Semara',
            'Aousserd',
            'Lagouira',
            'Tendrara',
            'Touissit',
            'Aknoul',
            'Matmata',
            'Ghafsai',
            'Tissa',
            'Tainaste',
            'Kerrouchen',
            'Bni Hadifa',
            'Tamassint',
            'Issaguen',
            'Ajdir',
            'Naima',
            'Tnin Sidi Lyamani',
            'Karia',
            'N\'Zalat Bni Amar',
            'Ahrara',
            'Bouguedra',
            'Ighoud',
            'Oulad Amrane',
            'Sebt Lamaarif',
            'Tafetachte',
            'Sidi Boubker',
            'Oued El Heimar',
            'Karia Ba Mohamed',
            'Thar Essouk',
            'Ain Karma',
            'Mhaya',
            'Zrarda',
            'Oulad Ghadbane',
            'Tafersit',
            'Saidia',
            'Lalla Takerkoust',
            'Skhinate',
            'Gueznaia',
            'Bni Drar',
            'Oued Amlil',
            'Sidi Rahel Chatai',
            'Echemmaia',
            'Jmaat Shaim',
            'Bir Jdid',
            'Azemmour',
            'Zmamra',
            'Ouled Frej',
            'Moulay Abdallah',
            'Sidi Ali Ben Hamdouche',
            'Kariat Arkmane',
            'Oulad Tayeb',
            'Bab Berrad',
            'Dar Gueddari',
            'Akka',
            'Moulay Bousselham',
            'Oualidia',
            'Sidi Bou Othmane',
            'Kehf Nsour',
            'Lakhsas',
            'Talmest',
            'Bni Chiker',
            'Tiztoutine',
            'Bab Taza',
            'Imouzzer Marmoucha',
            'Gourrama',
            'Ajdir',
            'Mhaya',
            'Oulad Ghadbane',
            'Zrarda',
            'Zoumi',
            'Ain Karma',
            'Thar Essouk',
            'Lagouira',
            'Ras El Ain',
            'Sidi Ali Ben Hamdouche',
            'Sebt Jahjouh',
            'Tiddas',
            'Zaouiat Bougrin',
            'Tafersit',
            'Touissit',
            'Saidia',
            'Lalla Takerkoust',
            'Skhinate',
            'Moulay Brahim',
            'Soualem',
            'Gueznaia',
            'Moulay Yacoub',
            'Matmata',
            'Kerouna',
            'Kassita',
            'Bni Hadifa',
            'Oued El Heimar',
            'Kerrouchen',
            'Tainaste',
            'Guisser',
            'Sidi Boubker',
            'Tamassint',
            'Assahrij',
            'Aghbalou Nssardane',
            'Tizi Ouasli',
            'Moqrisset',
            'Sebt Lamaarif',
            'Issaguen',
            'Bouguedra',
            'Brikcha',
            'Ighoud',
            'Ajdir, Taza',
            'Oulad Amrane',
            'Kettara',
            'Aoufous',
            'Tafetachte',
            'Naima',
            'Tnin Sidi Lyamani',
            'Karia',
            'N\'Zalat Bni Amar',
            'Ahrara',
            'Sidi Abdallah Ghiat'
        ];
        foreach ($villes as $ville) {
            Ville::create([
                'ville' => $ville
            ]);
        }
    }
}
